import { StyleSheet } from "react-native";
import { colors } from "../../modal/color.modal";

const styles = StyleSheet.create({
  containerWrap: {
    flex: 1,
    position: "relative",
  },
  container: {
    alignItems: "center",
  },
  imageWrap: {},
  postImage: {
    height: 260,
    width: 400,
    position: "relative",
  },
  backButton: {
    marginLeft: 18,
    marginTop: 20,
    paddingVertical: 6,
    paddingLeft: 5,
    paddingRight: 7,
    position: "absolute",
    borderRadius: 100,
    shadowColor: colors.secondary,
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.9,
    shadowRadius: 10,
    elevation: 10,
    backgroundColor: colors.white,
  },
  imageTextWrap: {
    marginLeft: 237,
    marginTop: 235,
    flexDirection: "row",
    position: "absolute",
    padding: 2.5,
    borderWidth: 1,
    borderStyle: "dashed",
    borderRadius: 30,
    borderColor: colors.secondary,
  },
  imageText: {
    fontSize: 10,
    color: colors.secondary,
  },
  imageIcon: {
    marginTop: 0.6,
    marginLeft: 2,
    size: 15,
    color: colors.secondary,
  },
  postTitle: {
    marginLeft: 20,
    marginRight: 20,
    marginTop: 20,
    fontSize: 30,
    fontWeight: "bold",
    color: colors.secondary,
  },
  locationDetails: {
    position: "absolute",
    marginLeft: 20,
    marginTop: 367,
    fontSize: 15,
  },
  locationTitle: {
    fontSize: 15,
    color: colors.grey,
  },
  locationText: {
    marginTop: 5,
  },
  ownerDetails: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginLeft: 20,
    marginTop: 110,
    paddingTop: 20,
    paddingBottom: 20,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.grey,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.grey,
  },
  ownedByTitle: {
    color: colors.grey,
  },
  ownedByMail: {
    fontSize: 15,
    fontWeight: "bold",
    marginTop: 5,
  },
  ownedByIcon: {
    justifyContent: "center",
    alignItems: "center",
    height: 50,
    width: 50,
    marginLeft: 170,
    borderRadius: 50,
    backgroundColor: colors.secondary,
  },
  ownedByIconText: {
    fontSize: 20,
    fontWeight: "bold",
    color: colors.primary,
  },
  descriptionDetails: {
    position: "absolute",
    marginTop: 540,
    marginLeft: 20,
    fontSize: 15,
  },
  descriptionTitle: {
    fontSize: 15,
    color: colors.grey,
  },
  descriptionText: {
    flex: 1,
    flexWrap: "wrap",
    marginTop: 10,
    marginRight: 15,
  },
  rentValueReserve: {
    justifyContent: "space-between",
    flexDirection: "row",
    position: "absolute",
    marginTop: 695,
    marginLeft: 20,
    paddingTop: 18,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.grey,
  },
  rentValueDetails: {
    flexDirection: "row",
  },
  rentValue: {
    fontSize: 18,
    fontWeight: "bold",
    marginTop: 10,
    color: colors.secondary,
  },
  rentValueText: {
    fontSize: 13,
    fontWeight: "bold",
    marginLeft: 5,
    marginTop: 15,
    color: colors.secondary,
  },
  postButton: {
    position: "absolute",
    borderRadius: 10,
    backgroundColor: colors.secondary,
  },
  postButtonText: {
    paddingVertical: 17,
    paddingHorizontal: 45,
    fontSize: 12,
    fontWeight: "bold",
    color: colors.white,
  },
});

export default styles;
